version: 2
jobs:
  build:
    docker:
      - image: golang
        environment:
          - PG_HOST=localhost
          - PG_USER=postgres
      - image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=gondolier
    working_directory: /go/src/github.com/DeKugelschieber/gondolier
    steps:
      - checkout
      - run: go get github.com/lib/pq
      - run: go test .
