version: 2
jobs:
  build:
    docker:
      - image: golang
        environment:
          - PG_HOST=localhost
          - PG_USER=postgres
      - image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=gondolier
    working_directory: /go/src/github.com/DeKugelschieber/gondolier
    steps:
      - checkout
      - run:
        name: Waiting for Postgres to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres && exit 1
      - run: go get github.com/lib/pq
      - run: go test .
